name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./project/requirements.txt
        pip install pytest
    - name: Run tests

      run: |
        cd project
        chmod +x pipeline.sh
        ./pipeline.sh
        echo "Tests are commented out due to high cost of running on GitHub Actions"
      run: |
        cd project
        chmod +x tests.sh
        ./tests.sh
      - name: Upload output files
        uses: actions/upload-artifact@v2
        with:
          name: output-files
          path: ./data/*.sqlite
